import pandas as pd
recipes = pd.read_csv("recipe.csv")
ingredients = pd.read_csv("ingredients.csv")
steps = pd.read_csv("steps.csv")
interactions = pd.read_csv("interactions.csv")
users = pd.read_csv("users.csv")
common_ing = ingredients['ingredient_name'].value_counts().head(10)
print(common_ing)
avg_prep = recipes['prep_time'].astype(float).mean()
print("Average prep time:", avg_prep)
difficulty_counts = recipes['difficulty'].value_counts()
print(difficulty_counts)
views = interactions[interactions['type'] == 'view']
top_views = views['recipe_id'].value_counts().head(10)
print(top_views)
likes = interactions[interactions['type'] == 'like']
top_likes = likes['recipe_id'].value_counts().head(10)
print(top_likes)
interactions["count"] = 1
engagement = interactions.groupby("recipe_id")["count"].sum().sort_values(ascending=False)
print(engagement.head(10))
ratings = interactions[interactions['rating'].notna()]
avg_ratings = ratings.groupby("recipe_id")["rating"].mean()
print(avg_ratings.head(10))
likes_count = likes.groupby("recipe_id")["type"].count().reset_index(name="likes")
merged = recipes.merge(likes_count, on="recipe_id", how="left")
merged['likes'] = merged['likes'].fillna(0)
correlation = merged['prep_time'].corr(merged['likes'])
print("Correlation:", correlation)
eng_count = interactions.groupby("recipe_id").size().reset_index(name="engagement")
merged_ing = ingredients.merge(eng_count, on="recipe_id")
ingredient_scores = merged_ing.groupby("ingredient_name")["engagement"].mean().sort_values(ascending=False)
print(ingredient_scores.head(10))
user_activity = interactions.groupby("user_id").size().sort_values(ascending=False)
print(user_activity.head(10))
